image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  # dune takes care of parallelization itself and does not like running in parallel
  CPU_CORES: "1"
  MAKE_TARGET: "all_with_examples"
  OCAML: "ocaml-variants.4.14.0+options ocaml-option-flambda"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  except:
  - triggers
  - schedules
  - api

## Build jobs
build-coq.8.20.0-timing:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.20.0   cerberus-lib git git+https://github.com/rems-project/cerberus.git#6e3e8be7a3f75b1f1cb0704dca8ef3945be0e413   dune version 3.18.1"
    DENY_WARNINGS: "1"
    OPAM_PKG: "1"
  only:
  - master@iris/refinedc
  - /^time/@iris/refinedc
  # timing only for master and time/ branches
  tags:
  - fp-timing

build-coq.8.20.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.20.0   cerberus-lib git git+https://github.com/rems-project/cerberus.git#6e3e8be7a3f75b1f1cb0704dca8ef3945be0e413   dune version 3.18.1"
    DENY_WARNINGS: "1"
  except:
  - master@iris/refinedc
  - /^time/@iris/refinedc
  - /^noci/@iris/refinedc
  - triggers
  - schedules
  - api

trigger-iris.dev:
  <<: *template
  variables:
    STDPP_REPO: "iris/stdpp"
    IRIS_REPO: "iris/iris"
    OPAM_PINS: "coq version 8.20.0   git+https://gitlab.mpi-sws.org/$STDPP_REPO#$STDPP_REV   coq-iris.dev git git+https://gitlab.mpi-sws.org/$IRIS_REPO#$IRIS_REV  cerberus-lib git git+https://github.com/rems-project/cerberus.git#6e3e8be7a3f75b1f1cb0704dca8ef3945be0e413   dune version 3.18.1"
  except:
  only:
  - triggers
  - schedules
  - api
