image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"
  MAKE_TARGET: "all_with_examples"
  OCAML: "ocaml-base-compiler.4.07.1"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  only:
  - master@iris/refinedc
  - /^ci/@iris/refinedc
  - /^time/@iris/refinedc
  except:
  - triggers
  - schedules
  - api

## Build jobs
# TODO: remove    z3 version 4.8.9-1 once https://github.com/Z3Prover/z3/issues/5405 and https://github.com/rems-project/cerberus/issues/180 are fixed
build-coq.8.12.0-timing:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.12.0   cerberus git git+https://github.com/rems-project/cerberus.git#8ef169cd84584f3b3e234333d7dd8cfc65c5b78d   z3 version 4.8.9-1"
    DENY_WARNINGS: "1"
    OPAM_PKG: "1"
  only:
  - master@iris/refinedc
  - /^time/@iris/refinedc
  # timing only for master and /time branches
  tags:
  - fp-timing

build-coq.8.12.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.12.0   cerberus git git+https://github.com/rems-project/cerberus.git#8ef169cd84584f3b3e234333d7dd8cfc65c5b78d   z3 version 4.8.9-1"
    DENY_WARNINGS: "1"
  only:
  - /^ci/@iris/refinedc

check-generated:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.12.0   cerberus git git+https://github.com/rems-project/cerberus.git#8ef169cd84584f3b3e234333d7dd8cfc65c5b78d   z3 version 4.8.9-1"
    DENY_WARNINGS: "1"
    MAKE_TARGET: "check_generate_all"
    # necessary because dune does not like running in parallel
    CPU_CORES: 1

trigger-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.12.dev   coq-stdpp.dev git git+https://gitlab.mpi-sws.org/iris/stdpp.git#$STDPP_REV   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#$IRIS_REV  cerberus git git+https://github.com/rems-project/cerberus.git#8ef169cd84584f3b3e234333d7dd8cfc65c5b78d   z3 version 4.8.9-1"
  except:
  only:
  - triggers
  - schedules
  - api
