image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"
  MAKE_TARGET: "all_with_examples"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  only:
  - master@iris/refinedc
  - /^ci/@iris/refinedc
  except:
  - triggers
  - schedules
  - api
  - merge_requests

## Build jobs

build-coq.8.11.2:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.11.2"
    DENY_WARNINGS: "1"
  tags:
  - fp-timing

build-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.11.dev   coq-stdpp.dev git git+https://gitlab.mpi-sws.org/iris/stdpp.git#$STDPP_REV   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#$IRIS_REV"
  except:
  only:
  - triggers
  - schedules
  - api
