# Custom RefinedC project file for the examples in the repository.

coq_root = "refinedc"

[cpp]
include = [ "include", "examples/include" ]
use_rc_include = false

[coq]
extra_theories = [
  "refinedc.lang",
  "refinedc.typing",
  "refinedc.typing.automation",
  "refinedc.lithium"
]
