# Custom RefinedC project file for the examples in the repository.

coq_root = "refinedc"
no_build = true

[cpp]
include = [ "include", "examples/include" , "linux/pkvm/include" ]
use_rc_include = false

[coq]
extra_theories = [
  "caesium",
  "refinedc.typing",
  "refinedc.typing.automation",
  "lithium"
]
